sudo: required

language: rust

services:
  - docker

env:
  - TIBERIUS_TEST_CONNECTION_STRING='server=tcp:127.0.0.1,1433;username=sa;password=tiberius123Linux;trustservercertificate=true'

rust:
  - stable

before_script:
  - docker pull microsoft/mssql-server-linux
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=tiberius123Linux' -p 1433:1433 -d microsoft/mssql-server-linux

script:
  - docker ps -a
  - cargo test --all
