environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    MSSQL:  SQL2016
    INSTANCE: MSSQL13.SQL2016
  - TARGET: i686-pc-windows-msvc
    MSSQL:  SQL2014
    INSTANCE: MSSQL12.SQL2014
  - TARGET: i686-pc-windows-gnu
    MSSQL:  SQL2012SP1
    INSTANCE: MSSQL11.SQL2012SP1
  - TARGET: x86_64-pc-windows-gnu
    MSSQL:  SQL2008R2SP2
    INSTANCE: MSSQL10_50.SQL2008R2SP2

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - ps: .\appveyor.ps1 ${env:MSSQL} ${env:INSTANCE}

build: false

test_script:
  - cargo test --target %TARGET%
